### ISSUE TITLE
uworld2anki error pop up

### ISSUE THREAD

**Issue by saucymeo** [firejake308/uw2a#1]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 5.14.2 PyQt 5.14.1
Platform: macOS-10.13.6-x86_64-i386-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-24 23:00:27
Add-ons possibly involved: ⁨UWorld2Anki⁩

----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 50139)
Traceback (most recent call last):
  File "socketserver", line 316, in _handle_request_noblock
  File "socketserver", line 347, in process_request
  File "socketserver", line 360, in finish_request
  File "/Users/Jazzy/Library/Application Support/Anki2/addons21/271205340/__init__.py", line 24, in __init__
    super().__init__(request, client_address, server)
  File "socketserver", line 747, in __init__
  File "http.server", line 432, in handle
  File "http.server", line 415, in handle_one_request
  File "http.server", line 487, in send_error
  File "socketserver", line 826, in write
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------

**Comment by firejake308** [comment]
Did this error occur as soon as you started Anki? Or when you clicked the button? Or randomly after running for a while?

**Comment by saucymeo** [comment]
> Did this error occur as soon as you started Anki? Or when you clicked the button? Or randomly after running for a while?

randomly running after a while

**Comment by firejake308** [comment]
Thanks for the report. Latest commit (3014594) should provide a patch. I can't test it on Mac, but I'll upload it to AnkiWeb soon, and hopefully someone will let me know if it breaks anything. For whatever reason, I can't upload the new version to AnkiWeb right now, though, so I'll try again in a few days.
